In [1]:
from keras.datasets import mnist
from matplotlib import pyplot

Using TensorFlow backend.
C:\Users\Karlemstrand\.conda\envs\tf\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Karlemstrand\.conda\envs\tf\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Karlemstrand\.conda\envs\tf\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Karlemstrand\.conda\envs\tf\lib\sit

In [2]:
# load train and test dataset
def load_dataset():
    # load dataset
    (trainX, trainY), (testX, testY) = mnist.load_data()
    
    # reshape dataset to have a single channel
    trainX = trainX.reshape((trainX.shape[0], 28, 28, 1))
    testX = testX.reshape((testX.shape[0], 28, 28, 1))
    
    # one hot encode target values
    trainY = to_categorical(trainY)
    testY = to_categorical(testY)
    
    return trainX, trainY, testX, testY

In [3]:
# preparation of the dataset

# 1. Normalise the pixel values in grayscale
def prep_pixels(train, test):
    # convert from integers to floats
    train_norm = train.astype('float32')
    test_norm = test.astype('float32')
    
    # normalize to range 0-1
    train_norm = train_norm / 255.0
    test_norm = test_norm / 255.0
    
    # return normalized images
    return train_norm, test_norm

In [4]:
# Model definition
# define cnn model
def define_model():
    model = Sequential()
    
    # 1. single convolutional layer with a modest number of filters (32) with a small filter size (3,3)
    model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)))
    
    # 2. max pooling layer
    model.add(MaxPooling2D((2, 2)))
    
    # 3. the filter maps is flattened to privide features to the classifier
    model.add(Flatten())
    
    # 4. 100 dense layer with 100 nodes
    model.add(Dense(100, activation='relu', kernel_initializer='he_uniform'))
    
    # 5. output layer to predict the probability distribution belonging to each of the 10 classes
    model.add(Dense(10, activation='softmax'))
    
    # compile model
    opt = SGD(lr=0.01, momentum=0.9)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [5]:
import numpy as np
from sklearn.model_selection import KFold

In [6]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([10, 20, 30, 40])

In [7]:
kf = KFold(n_splits=4)

In [8]:
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [9]:
kf.get_n_splits(X)

4

In [10]:
for train_index, test_index in kf.split(X):
    print(train_index)
    print(test_index)

[1 2 3]
[0]
[0 2 3]
[1]
[0 1 3]
[2]
[0 1 2]
[3]


In [11]:
X[train_index]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
X

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
X.shape

(4, 2)

In [14]:
X[3]

array([7, 8])

In [15]:
X[train_index].shape

(3, 2)